# Generated by Django 5.2.7 on 2026-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photo/products/djangodbmodelsfieldscharfield/', verbose_name='Фото'),
        ),
    ]
