# Generated by Django 5.2.7 on 2025-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_threshold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Порог для постоянного клиента')),
                ('regular_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Скидка на все товары (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Настройка лояльности',
                'verbose_name_plural': 'Настройки лояльности',
            },
        ),
    ]
