# Generated by Django 5.2.7 on 2025-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_remove_loyaltysettings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltysettings',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3, help_text='Стандартное количество дней на доставку', verbose_name='Срок доставки (дней)'),
        ),
    ]
