server {
    listen 8088;
    charset utf-8;

    # Logs
    access_log  /app/logs/access.log;
    error_log   /app/logs/error.log error;

    # Прокси для API
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarder-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header Content-Type $content_type;
        proxy_set_header Content-Length $content_length;
    }

    # Django admin-панель
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header X-Url-Scheme $scheme;
        proxy_set_header X-Forwarder-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    # Статические файлы backend
    location /static_files/ {
        alias /app/backend/static_files/;
    }
    
    # Медиа файлы backend
    location /media/ { 
        alias /app/backend/media/; 
    }
    
    # Иконка
    location /favicon.ico {
        root /app/frontend;
        access_log off; 
        log_not_found off; 
    }

    # Статические файлы frontend
    location /static/ {
        alias /app/frontend/static/;
        try_files $uri =404;
    }

    # Маршруты frontend
    location / {
        root /app/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
