# Generated by Django 5.2.7 on 2025-10-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('merchandiser', 'Товаровед'), ('sales_person', 'Менеджер по продажам'), ('admin', 'Администратор')], default='client', max_length=50, verbose_name='Роль'),
        ),
    ]
