# Generated by Django 5.2.7 on 2025-12-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('merchandiser', 'Товаровед'), ('account_manager', 'Клиент-менеджер'), ('salesperson', 'Продавец'), ('admin', 'Администратор')], default='client', max_length=50, verbose_name='Роль'),
        ),
    ]
